[project]
name = "vlasovexpermimentswithjax"
version = "0.1.0"
description = "Solve Vlasov-Poisson with Jax"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jax[cuda12]>=0.8.0",
    "matplotlib>=3.10.7",
]
